In [1]:
import pandas as pd

In [164]:
coffee=pd.read_csv('/Users/kseniaoblasova/Downloads/coffee.csv')
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [165]:
coffee['Price']=0.0
coffee

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25    0.0
1      Monday       Latte          15    0.0
2     Tuesday    Espresso          30    0.0
3     Tuesday       Latte          20    0.0
4   Wednesday    Espresso          35    0.0
5   Wednesday       Latte          25    0.0
6    Thursday    Espresso          40    0.0
7    Thursday       Latte          30    0.0
8      Friday    Espresso          45    0.0
9      Friday       Latte          35    0.0
10   Saturday    Espresso          45    0.0
11   Saturday       Latte          35    0.0
12     Sunday    Espresso          45    0.0
13     Sunday       Latte          35    0.0

In [166]:
import numpy as np
coffee['Price']=np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.05 )
coffee

          Day Coffee Type  Units Sold  Price
0      Monday    Espresso          25   3.99
1      Monday       Latte          15   5.05
2     Tuesday    Espresso          30   3.99
3     Tuesday       Latte          20   5.05
4   Wednesday    Espresso          35   3.99
5   Wednesday       Latte          25   5.05
6    Thursday    Espresso          40   3.99
7    Thursday       Latte          30   5.05
8      Friday    Espresso          45   3.99
9      Friday       Latte          35   5.05
10   Saturday    Espresso          45   3.99
11   Saturday       Latte          35   5.05
12     Sunday    Espresso          45   3.99
13     Sunday       Latte          35   5.05

In [167]:
coffee.columns=coffee.columns.str.lower().str.replace(' ', '_')
coffee

          day coffee_type  units_sold  price
0      Monday    Espresso          25   3.99
1      Monday       Latte          15   5.05
2     Tuesday    Espresso          30   3.99
3     Tuesday       Latte          20   5.05
4   Wednesday    Espresso          35   3.99
5   Wednesday       Latte          25   5.05
6    Thursday    Espresso          40   3.99
7    Thursday       Latte          30   5.05
8      Friday    Espresso          45   3.99
9      Friday       Latte          35   5.05
10   Saturday    Espresso          45   3.99
11   Saturday       Latte          35   5.05
12     Sunday    Espresso          45   3.99
13     Sunday       Latte          35   5.05

In [168]:
coffee['revenue']=coffee['units_sold']*coffee['price']
coffee

          day coffee_type  units_sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.05    75.75
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.05   101.00
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.05   126.25
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.05   151.50
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.05   176.75
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.05   176.75
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.05   176.75

In [169]:
coffee.loc[(coffee['units_sold']<20)&(coffee['revenue']<90)]

      day coffee_type  units_sold  price  revenue
1  Monday       Latte          15   5.05    75.75

In [170]:
len(coffee)
coffee.loc[len(coffee)]=['Sunday', 'Espresso', '45', '3.99', 45*3.99]
coffee

          day coffee_type units_sold price  revenue
0      Monday    Espresso         25  3.99    99.75
1      Monday       Latte         15  5.05    75.75
2     Tuesday    Espresso         30  3.99   119.70
3     Tuesday       Latte         20  5.05   101.00
4   Wednesday    Espresso         35  3.99   139.65
5   Wednesday       Latte         25  5.05   126.25
6    Thursday    Espresso         40  3.99   159.60
7    Thursday       Latte         30  5.05   151.50
8      Friday    Espresso         45  3.99   179.55
9      Friday       Latte         35  5.05   176.75
10   Saturday    Espresso         45  3.99   179.55
11   Saturday       Latte         35  5.05   176.75
12     Sunday    Espresso         45  3.99   179.55
13     Sunday       Latte         35  5.05   176.75
14     Sunday    Espresso         45  3.99   179.55

In [171]:
coffee.drop(index=14, inplace=True)
coffee

          day coffee_type units_sold price  revenue
0      Monday    Espresso         25  3.99    99.75
1      Monday       Latte         15  5.05    75.75
2     Tuesday    Espresso         30  3.99   119.70
3     Tuesday       Latte         20  5.05   101.00
4   Wednesday    Espresso         35  3.99   139.65
5   Wednesday       Latte         25  5.05   126.25
6    Thursday    Espresso         40  3.99   159.60
7    Thursday       Latte         30  5.05   151.50
8      Friday    Espresso         45  3.99   179.55
9      Friday       Latte         35  5.05   176.75
10   Saturday    Espresso         45  3.99   179.55
11   Saturday       Latte         35  5.05   176.75
12     Sunday    Espresso         45  3.99   179.55
13     Sunday       Latte         35  5.05   176.75

In [172]:
coffee.loc[14]=['Sunday', 'Americano', 33, 4.20, 33*4.20]
coffee

          day coffee_type units_sold price  revenue
0      Monday    Espresso         25  3.99    99.75
1      Monday       Latte         15  5.05    75.75
2     Tuesday    Espresso         30  3.99   119.70
3     Tuesday       Latte         20  5.05   101.00
4   Wednesday    Espresso         35  3.99   139.65
5   Wednesday       Latte         25  5.05   126.25
6    Thursday    Espresso         40  3.99   159.60
7    Thursday       Latte         30  5.05   151.50
8      Friday    Espresso         45  3.99   179.55
9      Friday       Latte         35  5.05   176.75
10   Saturday    Espresso         45  3.99   179.55
11   Saturday       Latte         35  5.05   176.75
12     Sunday    Espresso         45  3.99   179.55
13     Sunday       Latte         35  5.05   176.75
14     Sunday   Americano         33   4.2   138.60

In [173]:
coffee=coffee[coffee['coffee_type'].isin(['Latte', 'Espresso'])]
coffee

          day coffee_type units_sold price  revenue
0      Monday    Espresso         25  3.99    99.75
1      Monday       Latte         15  5.05    75.75
2     Tuesday    Espresso         30  3.99   119.70
3     Tuesday       Latte         20  5.05   101.00
4   Wednesday    Espresso         35  3.99   139.65
5   Wednesday       Latte         25  5.05   126.25
6    Thursday    Espresso         40  3.99   159.60
7    Thursday       Latte         30  5.05   151.50
8      Friday    Espresso         45  3.99   179.55
9      Friday       Latte         35  5.05   176.75
10   Saturday    Espresso         45  3.99   179.55
11   Saturday       Latte         35  5.05   176.75
12     Sunday    Espresso         45  3.99   179.55
13     Sunday       Latte         35  5.05   176.75

In [174]:
coffee.iloc[::2,1]='Americano'
coffee

          day coffee_type units_sold price  revenue
0      Monday   Americano         25  3.99    99.75
1      Monday       Latte         15  5.05    75.75
2     Tuesday   Americano         30  3.99   119.70
3     Tuesday       Latte         20  5.05   101.00
4   Wednesday   Americano         35  3.99   139.65
5   Wednesday       Latte         25  5.05   126.25
6    Thursday   Americano         40  3.99   159.60
7    Thursday       Latte         30  5.05   151.50
8      Friday   Americano         45  3.99   179.55
9      Friday       Latte         35  5.05   176.75
10   Saturday   Americano         45  3.99   179.55
11   Saturday       Latte         35  5.05   176.75
12     Sunday   Americano         45  3.99   179.55
13     Sunday       Latte         35  5.05   176.75

In [175]:
coffee['coffee_type']=coffee['coffee_type'].str.replace('Americano', 'Espresso')
coffee

          day coffee_type units_sold price  revenue
0      Monday    Espresso         25  3.99    99.75
1      Monday       Latte         15  5.05    75.75
2     Tuesday    Espresso         30  3.99   119.70
3     Tuesday       Latte         20  5.05   101.00
4   Wednesday    Espresso         35  3.99   139.65
5   Wednesday       Latte         25  5.05   126.25
6    Thursday    Espresso         40  3.99   159.60
7    Thursday       Latte         30  5.05   151.50
8      Friday    Espresso         45  3.99   179.55
9      Friday       Latte         35  5.05   176.75
10   Saturday    Espresso         45  3.99   179.55
11   Saturday       Latte         35  5.05   176.75
12     Sunday    Espresso         45  3.99   179.55
13     Sunday       Latte         35  5.05   176.75

In [176]:
coffee['cost_of_production']=0

In [177]:
coffee

          day coffee_type units_sold price  revenue  cost_of_production
0      Monday    Espresso         25  3.99    99.75                   0
1      Monday       Latte         15  5.05    75.75                   0
2     Tuesday    Espresso         30  3.99   119.70                   0
3     Tuesday       Latte         20  5.05   101.00                   0
4   Wednesday    Espresso         35  3.99   139.65                   0
5   Wednesday       Latte         25  5.05   126.25                   0
6    Thursday    Espresso         40  3.99   159.60                   0
7    Thursday       Latte         30  5.05   151.50                   0
8      Friday    Espresso         45  3.99   179.55                   0
9      Friday       Latte         35  5.05   176.75                   0
10   Saturday    Espresso         45  3.99   179.55                   0
11   Saturday       Latte         35  5.05   176.75                   0
12     Sunday    Espresso         45  3.99   179.55                   0
13     Sunday       Latte         35  5.05   176.75                   0

In [178]:
coffee['cost_of_production']=np.where(coffee['coffee_type']=='Espresso', 1, 1.5)
coffee

          day coffee_type units_sold price  revenue  cost_of_production
0      Monday    Espresso         25  3.99    99.75                 1.0
1      Monday       Latte         15  5.05    75.75                 1.5
2     Tuesday    Espresso         30  3.99   119.70                 1.0
3     Tuesday       Latte         20  5.05   101.00                 1.5
4   Wednesday    Espresso         35  3.99   139.65                 1.0
5   Wednesday       Latte         25  5.05   126.25                 1.5
6    Thursday    Espresso         40  3.99   159.60                 1.0
7    Thursday       Latte         30  5.05   151.50                 1.5
8      Friday    Espresso         45  3.99   179.55                 1.0
9      Friday       Latte         35  5.05   176.75                 1.5
10   Saturday    Espresso         45  3.99   179.55                 1.0
11   Saturday       Latte         35  5.05   176.75                 1.5
12     Sunday    Espresso         45  3.99   179.55                 1.0
13     Sunday       Latte         35  5.05   176.75                 1.5

In [179]:
coffee['profit']=coffee['revenue']-coffee['cost_of_production']
coffee

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25

In [180]:
new_data=pd.DataFrame({'day':['Monday', 'Wednesday', 'Friday'], 
                       'coffee_type':['Americano', 'Cold Brew', 'Frapuccino'],
                       'units_sold':[11,22,34],
                       'price':[3.45, 3.99, 6.05],
                       'cost_of_production':[1.2,1.4,2]})
new_data.insert(loc=4, column='revenue', value=new_data['units_sold']*new_data['price'])

new_data

         day coffee_type  units_sold  price  revenue  cost_of_production
0     Monday   Americano          11   3.45    37.95                 1.2
1  Wednesday   Cold Brew          22   3.99    87.78                 1.4
2     Friday  Frapuccino          34   6.05   205.70                 2.0

In [181]:
new_data.insert(loc=len(new_data.columns), column='profit', value=new_data['revenue']-new_data['cost_of_production'])
new_data

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Americano,11,3.45,37.95,1.2,36.75
1,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
2,Friday,Frapuccino,34,6.05,205.70,2.0,203.70

In [182]:
coffee=pd.concat([coffee, new_data], ignore_index=True)
coffee

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25
14,Monday,Americano,11,3.45,37.95,1.2,36.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
16,Friday,Frapuccino,34,6.05,205.70,2.0,203.70

In [183]:
coffee.drop(coffee[coffee['coffee_type']=='Frapuccino'].index, inplace=True)
coffee

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25
14,Monday,Americano,11,3.45,37.95,1.2,36.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38

In [184]:
day_order=['Monday', 'Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
coffee['day']=pd.Categorical(coffee['day'], categories=day_order, ordered=True)
sorted_by_day=coffee.sort_values('day')
sorted_by_day

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
14,Monday,Americano,11,3.45,37.95,1.2,36.75
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25

In [185]:
sorted_by_revenue=coffee.sort_values(by='revenue', ascending=True)
sorted_by_revenue

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
14,Monday,Americano,11,3.45,37.95,1.2,36.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
9,Friday,Latte,35,5.05,176.75,1.5,175.25
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
13,Sunday,Latte,35,5.05,176.75,1.5,175.25
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55

In [186]:
sorted_by_day

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
14,Monday,Americano,11,3.45,37.95,1.2,36.75
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25

In [187]:
sorted_by_day.loc[14]=['Sunday', 'Espresso', 45, 3.99, 179.55, 1.0, 178.55]
sorted_by_day

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
14,Sunday,Espresso,45,3.99,179.55,1.0,178.55
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25

In [188]:
sorted_by_day=sorted_by_day.drop_duplicates()
sorted_by_day

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
14,Sunday,Espresso,45,3.99,179.55,1.0,178.55
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
13,Sunday,Latte,35,5.05,176.75,1.5,175.25

In [189]:
sorted_by_day=sorted_by_day.sort_values('day')
sorted_by_day

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
14,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25

In [190]:
sorted_by_day=sorted_by_day.reset_index(drop=True)
sorted_by_day

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
6,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38
7,Thursday,Espresso,40,3.99,159.60,1.0,158.60
8,Thursday,Latte,30,5.05,151.50,1.5,150.00
9,Friday,Espresso,45,3.99,179.55,1.0,178.55
10,Friday,Latte,35,5.05,176.75,1.5,175.25
11,Saturday,Espresso,45,3.99,179.55,1.0,178.55
12,Saturday,Latte,35,5.05,176.75,1.5,175.25
13,Sunday,Espresso,45,3.99,179.55,1.0,178.55
14,Sunday,Latte,35,5.05,176.75,1.5,175.25

In [191]:
sorted_by_day.drop(columns=['level_0', 'index'], inplace=True)
sorted_by_day

KeyError: "['level_0', 'index'] not found in axis"

In [ ]:
coffee

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit
0,Monday,Espresso,25,3.99,99.75,1.0,98.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00
8,Friday,Espresso,45,3.99,179.55,1.0,178.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25
14,Monday,Americano,11,3.45,37.95,1.2,36.75
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38

In [ ]:
coffee['revenue_squared']=coffee['revenue'].apply(lambda x: x**2)
coffee

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit,revenue_squared
0,Monday,Espresso,25,3.99,99.75,1.0,98.75,9950.0625
1,Monday,Latte,15,5.05,75.75,1.5,74.25,5738.0625
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70,14328.0900
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50,10201.0000
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65,19502.1225
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75,15939.0625
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60,25472.1600
7,Thursday,Latte,30,5.05,151.50,1.5,150.00,22952.2500
8,Friday,Espresso,45,3.99,179.55,1.0,178.55,32238.2025
9,Friday,Latte,35,5.05,176.75,1.5,175.25,31240.5625
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55,32238.2025
11,Saturday,Latte,35,5.05,176.75,1.5,175.25,31240.5625
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55,32238.2025
13,Sunday,Latte,35,5.05,176.75,1.5,175.25,31240.5625
14,Monday,Americano,11,3.45,37.95,1.2,36.75,1440.2025
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38,7705.3284

In [ ]:
coffee['revenue_squared']=coffee['revenue_squared'].apply(lambda x: np.sqrt(x))
coffee

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit,revenue_squared
0,Monday,Espresso,25,3.99,99.75,1.0,98.75,99.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25,75.75
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70,119.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50,101.00
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65,139.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75,126.25
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60,159.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00,151.50
8,Friday,Espresso,45,3.99,179.55,1.0,178.55,179.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25,176.75
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55,179.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25,176.75
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55,179.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25,176.75
14,Monday,Americano,11,3.45,37.95,1.2,36.75,37.95
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38,87.78

In [ ]:
coffee.rename(columns={'revenue_squared':'revenue'}, inplace=True)
coffee

,day,coffee_type,units_sold,price,revenue,cost_of_production,profit,revenue
0,Monday,Espresso,25,3.99,99.75,1.0,98.75,99.75
1,Monday,Latte,15,5.05,75.75,1.5,74.25,75.75
2,Tuesday,Espresso,30,3.99,119.70,1.0,118.70,119.70
3,Tuesday,Latte,20,5.05,101.00,1.5,99.50,101.00
4,Wednesday,Espresso,35,3.99,139.65,1.0,138.65,139.65
5,Wednesday,Latte,25,5.05,126.25,1.5,124.75,126.25
6,Thursday,Espresso,40,3.99,159.60,1.0,158.60,159.60
7,Thursday,Latte,30,5.05,151.50,1.5,150.00,151.50
8,Friday,Espresso,45,3.99,179.55,1.0,178.55,179.55
9,Friday,Latte,35,5.05,176.75,1.5,175.25,176.75
10,Saturday,Espresso,45,3.99,179.55,1.0,178.55,179.55
11,Saturday,Latte,35,5.05,176.75,1.5,175.25,176.75
12,Sunday,Espresso,45,3.99,179.55,1.0,178.55,179.55
13,Sunday,Latte,35,5.05,176.75,1.5,175.25,176.75
14,Monday,Americano,11,3.45,37.95,1.2,36.75,37.95
15,Wednesday,Cold Brew,22,3.99,87.78,1.4,86.38,87.78