In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.0

# Series

In [24]:
data=[100,102,104, 200, 202]
series=pd.Series(data, index=['a','b','c', 'd', 'e'])
series.loc['c']=105
print(series[series<200])

a    100
b    102
c    105
dtype: int64

In [32]:
calories={'Day 1':1750, 'Day 2': 2100, 'Day 3': 1700}
series_a=pd.Series(calories)
series_a.loc['Day 3']+=300
print(series_a[series_a<2000])

Day 1    1750
dtype: int64

# DataFrames

In [48]:
data={'Name':['Kseniia', 'Iuliia', 'Aleksandr'],
      'Age':[18,52,53]}

df=pd.DataFrame(data, index=['Fam member 1', 'Fam member 2', 'Fam member 3' ])
#add a new column

df['Job']=['Student','N/A','Constructor']

#Add a new row
new_rows=pd.DataFrame([{'Name':'Yana', 'Age':29, 'Job': 'Cosmetologist'},
                      {'Name':'Oleksandr', 'Age':35, 'Job': 'N/A'}], 
                     index=['Fam member 4', 'Fam member 5'])

df=pd.concat([df, new_rows])


print(df)

                   Name  Age            Job
Fam member 1    Kseniia   18        Student
Fam member 2     Iuliia   52            N/A
Fam member 3  Aleksandr   53    Constructor
Fam member 4       Yana   29  Cosmetologist
Fam member 5  Oleksandr   35            N/A

# Work with imported data

In [105]:
df=pd.read_csv('/Users/kseniaoblasova/Desktop/tallest_people_in_the_world.csv')
df.head()

,id,name,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition,is_alive
0,1,John F. Carroll,Male,USA,North America,264,8 ft 8 in,140.0,1932,1969.0,37,NaN,Acromegaly,0
1,2,Robert Wadlow,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism,0
2,3,John Rogan,Male,USA,North America,267,8 ft 9 in,79.0,1868,1905.0,37,Seller,Gigantism,0
3,4,Willie Camper,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism,0
4,5,Siah Khan,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism,0

In [86]:

df.loc['John F. Carroll':'Siah Khan', ['height_cm', 'country']]

                 height_cm country
name
John F. Carroll        264     USA
Robert Wadlow          272     USA
John Rogan             267     USA
Willie Camper          260     USA
Siah Khan              259    Iran

In [88]:
df.iloc[0:11:2, 1:7]

,gender,country,continent,height_cm,height_ft_in,weight_kg
name,,,,,,
John F. Carroll,Male,USA,North America,264,8 ft 8 in,140.0
John Rogan,Male,USA,North America,267,8 ft 9 in,79.0
Siah Khan,Male,Iran,Asia,259,8 ft 6 in,155.0
Vrolijk de Beers,Male,Malawi,Africa,246,8 ft 1 in,130.0
Pornchai Saosri,Male,Thailand,Asia,269,8 ft 10 in,NaN
Edouard Beaupre,Male,Canada,North America,251,8 ft 3 in,170.0

In [97]:
name=input('Enter a name: ')
try:
    print(df.loc[name])
except KeyError:
    print('There is no such name. Sorry.')

Enter a name:  ejksjsj

There is no such name. Sorry.

In [99]:
extra_tall=df[df['height_cm']>=250]
extra_tall

,id,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition,is_alive
name,,,,,,,,,,,,,
John F. Carroll,1,Male,USA,North America,264,8 ft 8 in,140.0,1932,1969.0,37,NaN,Acromegaly,0
Robert Wadlow,2,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism,0
John Rogan,3,Male,USA,North America,267,8 ft 9 in,79.0,1868,1905.0,37,Seller,Gigantism,0
Willie Camper,4,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism,0
Siah Khan,5,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism,0
Akashi Shiganosuke,6,Male,Japan,Asia,254,8 ft 4 in,185.0,1600,1649.0,49,Athlete,Gigantism,0
Ho Van Trung,8,Male,Vietnam,Asia,257,8 ft 5 in,158.0,1984,2019.0,35,Farmer,Gigantism,0
Pornchai Saosri,9,Male,Thailand,Asia,269,8 ft 10 in,NaN,1989,2015.0,26,NaN,Gigantism,0
Edouard Beaupre,11,Male,Canada,North America,251,8 ft 3 in,170.0,1881,1904.0,23,Entertainer,Gigantism,0
Parimal Barman,12,Male,Bangladesh,Asia,251,8 ft 3 in,NaN,1962,1991.0,29,NaN,Gigantism,0
Vaino Myllyrinne,13,Male,Finland,Europe,251,8 ft 3 in,197.0,1909,1963.0,54,Soldier,Gigantism,0
Vikas Uppal,14,Male,India,Asia,251,8 ft 3 in,NaN,1986,2007.0,21,NaN,Gigantism,0
Sultan Kosen,15,Male,Turkey,Asia,251,8 ft 2.8 in,137.0,1982,NaN,44,Farmer,Acromegaly,1
Trijntje Keever,133,Female,Netherlands,Europe,254,8 ft 4 in,NaN,1616,1633.0,17,NaN,Gigantism,0

In [100]:
extra_heavy=df[df['weight_kg']>=150]
extra_heavy

,id,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition,is_alive
name,,,,,,,,,,,,,
Robert Wadlow,2,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism,0
Willie Camper,4,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism,0
Siah Khan,5,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism,0
Akashi Shiganosuke,6,Male,Japan,Asia,254,8 ft 4 in,185.0,1600,1649.0,49,Athlete,Gigantism,0
Ho Van Trung,8,Male,Vietnam,Asia,257,8 ft 5 in,158.0,1984,2019.0,35,Farmer,Gigantism,0
Edouard Beaupre,11,Male,Canada,North America,251,8 ft 3 in,170.0,1881,1904.0,23,Entertainer,Gigantism,0
Vaino Myllyrinne,13,Male,Finland,Europe,251,8 ft 3 in,197.0,1909,1963.0,54,Soldier,Gigantism,0
Gabriel Estevao Monjane,21,Male,Mozambique,Africa,246,8 ft 1 in,190.0,1944,1990.0,46,Entertainer,Gigantism,0
Suparwono,32,Male,Indonesia,Asia,242,7 ft 11 in,160.0,1985,2012.0,27,NaN,Gigantism,0
Miguel Joaquin Eleicegui,34,Male,Spain,Europe,242,7 ft 11 in,166.0,1818,1861.0,43,Entertainer,Gigantism,0
Josef Drasal,39,Male,Czech Republic,Europe,242,7 ft 11 in,186.0,1841,1886.0,45,Entertainer,Gigantism,0
Fyodor Makhnov,42,Male,Belarus,Europe,239,7 ft 10 in,182.0,1878,1912.0,34,Entertainer,Acromegaly,0
Sun Mingming,46,Male,China,Asia,236,7 ft 9 in,168.0,1983,NaN,43,Athlete,Acromegaly,1
Bao Xishun,47,Male,China,Asia,236,7 ft 9 in,165.0,1951,NaN,75,Farmer,Gigantism,1
Angus MacAskill,50,Male,UK,Europe,236,7 ft 9 in,230.0,1825,1863.0,38,Entertainer,Gigantism,0
Joelison Fernandes da Silva,51,Male,Brazil,South America,236,7 ft 9 in,169.0,1985,NaN,41,Athlete,Acromegaly,1
Frederick Kempster,53,Male,UK,Europe,237,7 ft 9.3 in,170.0,1889,1918.0,29,Entertainer,Gigantism,0
Martin Van Buren Bates,54,Male,USA,North America,236,7 ft 9 in,175.0,1837,1919.0,81,Soldier,Gigantism,0
Kaba uulu Kojomkul,57,Male,Kyrgyzstan,Asia,230,7 ft 6.5 in,165.0,1889,1955.0,66,Farmer,Gigantism,0
Uvais Akhtaev,58,Male,Russia,Europe,236,7 ft 9 in,160.0,1930,1978.0,48,Athlete,Gigantism,0
Bob Wegner,67,Male,USA,North America,232,7 ft 7.5 in,204.0,1993,NaN,33,Athlete,Gigantism,1
Igor Vovkovinskiy,68,Male,USA,North America,235,7 ft 8.3 in,172.0,1982,2021.0,39,Actor,Acromegaly,0
Johann K. Petursson,77,Male,Iceland,Europe,234,7 ft 8 in,163.0,1913,1984.0,71,Entertainer,Gigantism,0
Jorge Gonzalez,84,Male,Argentina,South America,231,7 ft 7 in,210.0,1966,2010.0,44,Athlete,Acromegaly,0
Hussain Bisad,85,Male,Somalia,Africa,232,7 ft 7 in,210.0,1975,NaN,51,NaN,Acromegaly,1
Kenny George,87,Male,USA,North America,231,7 ft 7 in,160.0,1986,NaN,40,Athlete,Acromegaly,1
Sim Bhullar,102,Male,Canada,North America,226,7 ft 5 in,163.0,1992,NaN,34,Athlete,Genetic,1
Anna Haining Bates,136,Female,Canada,North America,241,7 ft 11 in,159.0,1846,1888.0,41,Entertainer,Gigantism,0
Siddiqa Parveen,138,Female,India,Asia,233,7 ft 8 in,160.0,1985,2014.0,29,NaN,Gigantism,0
Yao Defen,139,Female,China,Asia,234,7 ft 8 in,179.0,1972,2012.0,40,Entertainer,Acromegaly,0
Sandy Allen,141,Female,USA,North America,232,7 ft 7 in,209.0,1955,2008.0,53,Actor,Gigantism,0

In [101]:
from_russia=df[df['country']=='Russia']
from_russia

,id,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition,is_alive
name,,,,,,,,,,,,,
Uvais Akhtaev,58,Male,Russia,Europe,236,7 ft 9 in,160.0,1930,1978.0,48,Athlete,Gigantism,0
Nikolai Pankratov,63,Male,Russia,Europe,235,7 ft 8.5 in,NaN,1946,2003.0,57,NaN,Gigantism,0

In [103]:
gigantic_entertainers=df[(df['medical_condition']=='Gigantism')&
                        (df['occupation']=='Entertainer')]
gigantic_entertainers

,id,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition,is_alive
name,,,,,,,,,,,,,
Robert Wadlow,2,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism,0
Willie Camper,4,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism,0
Siah Khan,5,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism,0
Vrolijk de Beers,7,Male,Malawi,Africa,246,8 ft 1 in,130.0,1925,1961.0,36,Entertainer,Gigantism,0
Edouard Beaupre,11,Male,Canada,North America,251,8 ft 3 in,170.0,1881,1904.0,23,Entertainer,Gigantism,0
Gabriel Estevao Monjane,21,Male,Mozambique,Africa,246,8 ft 1 in,190.0,1944,1990.0,46,Entertainer,Gigantism,0
James Toller,24,Male,UK,Europe,244,8 ft 0 in,NaN,1795,1818.0,23,Entertainer,Gigantism,0
Zhan Shichai,25,Male,China,Asia,244,8 ft 0 in,NaN,1841,1893.0,52,Entertainer,Gigantism,0
Patrick Cotter O'Brien,28,Male,Ireland,Europe,244,8 ft 0 in,NaN,1760,1806.0,46,Entertainer,Gigantism,0
Albert Johan Kramer,33,Male,Netherlands,Europe,242,7 ft 11 in,NaN,1897,1976.0,79,Entertainer,Gigantism,0
Miguel Joaquin Eleicegui,34,Male,Spain,Europe,242,7 ft 11 in,166.0,1818,1861.0,43,Entertainer,Gigantism,0
Josef Drasal,39,Male,Czech Republic,Europe,242,7 ft 11 in,186.0,1841,1886.0,45,Entertainer,Gigantism,0
Angus MacAskill,50,Male,UK,Europe,236,7 ft 9 in,230.0,1825,1863.0,38,Entertainer,Gigantism,0
William Bradley,52,Male,UK,Europe,236,7 ft 9 in,NaN,1787,1820.0,33,Entertainer,Gigantism,0
Frederick Kempster,53,Male,UK,Europe,237,7 ft 9.3 in,170.0,1889,1918.0,29,Entertainer,Gigantism,0
Louis Moilanen,55,Male,USA,North America,246,8 ft 1 in,NaN,1886,1913.0,27,Entertainer,Gigantism,0
Ted Evans,62,Male,UK,Europe,235,7 ft 8.5 in,NaN,1924,1958.0,34,Entertainer,Gigantism,0
Polipaka Gattaiah,69,Male,India,Asia,230,7 ft 6.5 in,NaN,1975,2015.0,40,Entertainer,Gigantism,0
Alam Channa,76,Male,Pakistan,Asia,232,7 ft 7 in,NaN,1953,1998.0,45,Entertainer,Gigantism,0
Johann K. Petursson,77,Male,Iceland,Europe,234,7 ft 8 in,163.0,1913,1984.0,71,Entertainer,Gigantism,0
Daniel Cajanus,79,Male,Finland,Europe,234,7 ft 8 in,NaN,1704,1749.0,45,Entertainer,Gigantism,0
Agustin Luengo Capilla,81,Male,Spain,Europe,235,7 ft 8.5 in,NaN,1849,1875.0,26,Entertainer,Gigantism,0
Charles Byrne,89,Male,Ireland,Europe,231,7 ft 7 in,NaN,1761,1783.0,22,Entertainer,Gigantism,0
Ralph Madsen,96,Male,USA,North America,228,7 ft 6 in,105.0,1897,1948.0,51,Entertainer,Gigantism,0
Ella Ewing,134,Female,USA,North America,224,7 ft 4 in,115.0,1872,1913.0,41,Entertainer,Gigantism,0
Anna Haining Bates,136,Female,Canada,North America,241,7 ft 11 in,159.0,1846,1888.0,41,Entertainer,Gigantism,0
Maria Fassnauer,149,Female,Italy,Europe,222,7 ft 3.5 in,NaN,1879,1917.0,38,Entertainer,Gigantism,0
Kristina Larsdotter,156,Female,Sweden,Europe,210,6 ft 10.7 in,NaN,1819,1854.0,35,Entertainer,Gigantism,0

In [108]:
df.mean(numeric_only=True)

id              79.000000
height_cm      233.904459
weight_kg      143.945946
birth_year    1938.471338
death_year    1942.000000
lifespan        42.554140
is_alive         0.464968
dtype: float64

In [110]:
df.sum(numeric_only=True)

id             12403.0
height_cm      36723.0
weight_kg      10652.0
birth_year    304340.0
death_year    163128.0
lifespan        6681.0
is_alive          73.0
dtype: float64

In [113]:
df.min(numeric_only=True)

id               1.0
height_cm      210.0
weight_kg       79.0
birth_year    1600.0
death_year    1633.0
lifespan        16.0
is_alive         0.0
dtype: float64

In [114]:
df.max(numeric_only=True)

id             157.0
height_cm      272.0
weight_kg      230.0
birth_year    2010.0
death_year    2025.0
lifespan        98.0
is_alive         1.0
dtype: float64

In [115]:
df.count()

id                   157
name                 157
gender               157
country              157
continent            157
height_cm            157
height_ft_in         157
weight_kg             74
birth_year           157
death_year            84
lifespan             157
occupation           111
medical_condition    157
is_alive             157
dtype: int64

In [120]:
print(df['height_cm'].sum())

36723

In [126]:
group=df.groupby('birth_year')
group['height_cm'].max()

birth_year
1600    254
1616    254
1704    234
1760    244
1761    231
       ...
2002    224
2004    224
2006    236
2007    220
2010    222
Name: height_cm, Length: 94, dtype: int64

In [127]:
df

,id,name,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition,is_alive
0,1,John F. Carroll,Male,USA,North America,264,8 ft 8 in,140.0,1932,1969.0,37,NaN,Acromegaly,0
1,2,Robert Wadlow,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism,0
2,3,John Rogan,Male,USA,North America,267,8 ft 9 in,79.0,1868,1905.0,37,Seller,Gigantism,0
3,4,Willie Camper,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism,0
4,5,Siah Khan,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,6 ft 10.7 in,NaN,1964,NaN,62,Athlete,Genetic,1
153,154,Miranda Weber,Female,Canada,North America,211,6 ft 11 in,NaN,1982,NaN,44,Athlete,Genetic,1
154,155,Uljana Semjonova,Female,Latvia,Europe,213,7 ft 0 in,120.0,1952,NaN,74,Athlete,Genetic,1
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,6 ft 10.7 in,NaN,1819,1854.0,35,Entertainer,Gigantism,0
156,157,Han Xu,Female,China,Asia,211,6 ft 11 in,88.0,1999,NaN,27,Athlete,Genetic,1

In [149]:
df=df.drop(columns=['medical_condition'], errors='ignore')
df['country']=df['country'].replace({'USA':'United States'})
df

,id,name,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,occupation
0,1,MALE,MALE,United States,North America,264,8 ft 8 in,140.0,1932,1969.0,NaN
1,2,MALE,MALE,United States,North America,272,8 ft 11 in,199.0,1918,1940.0,Entertainer
2,3,MALE,MALE,United States,North America,267,8 ft 9 in,79.0,1868,1905.0,Seller
3,4,MALE,MALE,United States,North America,260,8 ft 6.3 in,170.0,1924,1943.0,Entertainer
4,5,MALE,MALE,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,Entertainer
...,...,...,...,...,...,...,...,...,...,...,...
140,141,FEMALE,FEMALE,United States,North America,232,7 ft 7 in,209.0,1955,2008.0,Actor
146,147,FEMALE,FEMALE,Poland,Europe,218,7 ft 2 in,101.0,1974,2011.0,Athlete
151,152,FEMALE,FEMALE,Thailand,Asia,212,6 ft 11.5 in,127.0,1992,2016.0,NaN
154,155,FEMALE,FEMALE,Latvia,Europe,213,7 ft 0 in,120.0,1952,NaN,Athlete
156,157,FEMALE,FEMALE,China,Asia,211,6 ft 11 in,88.0,1999,NaN,Athlete