In [1]:
import pandas as pd

In [90]:
bios=pd.read_csv('/Users/kseniaoblasova/Downloads/bios.csv')
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [91]:
bios.drop(columns=bios.filter(like='date'), inplace=True)
bios

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [92]:
bios.filter(regex=r'^\w+_\w+$')

,athlete_id,born_city,born_region,born_country,height_cm,weight_kg
0,1,Bordeaux,Gironde,FRA,NaN,NaN
1,2,Meulan,Yvelines,FRA,183.0,76.0
2,3,Biarritz,Pyrénées-Atlantiques,FRA,183.0,76.0
3,4,Paris VIIIe,Paris,FRA,168.0,64.0
4,5,Wandsworth,England,GBR,NaN,NaN
...,...,...,...,...,...,...
145495,149222,Serov,Sverdlovsk,RUS,167.0,61.0
145496,149223,Moskva (Moscow),Moskva,RUS,168.0,65.0
145497,149224,Kotlas,Arkhangelsk,RUS,163.0,55.0
145498,149225,Niort,Deux-Sèvres,FRA,166.0,NaN
145499,149814,Dulwich Hill,New South Wales,AUS,NaN,NaN

In [94]:
bios.rename(columns={'athlete_id':'id'}, inplace=True)
bios

,id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [97]:
bios.columns=bios.columns.str.replace('_area', '_region')
bios

,id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [100]:
del bios['double_weight_kg']
bios

,id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [110]:
bios=bios.add_prefix('athlete_')
bios

,athlete_id,athlete_name,athlete_born_city,athlete_born_region,athlete_born_country,athlete_NOC,athlete_height_cm,athlete_weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [111]:
bios.columns=bios.columns.str.replace('athlete_', '')
bios

,id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,149223,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,149224,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,149225,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,149814,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [112]:
del bios['id']
bios

,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...
145495,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [113]:
bios.insert(loc=0, column='athlete_id', value=range(1, len(bios)+1))
bios

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,145496,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,145497,Valeriya Merkusheva,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0
145497,145498,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,145499,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,145500,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN

In [129]:
bios.born_city=bios['born_city'].str.replace('Moskva (Moscow)', 'Moscow')
bios.born_region=bios['born_region'].str.replace('Moskva', 'Moscow')
bios[bios['born_region']=='Moscow'].sample(20)

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
10896,10897,Aleksandr Degtyaryov,Tolmachevo,Moscow,RUS,Soviet Union,185.0,83.0
32598,32599,Nataliya Deryugina,Moscow,Moscow,RUS,Unified Team,NaN,NaN
105511,105512,Vadim Strogalyev,Moscow,Moscow,RUS,Russian Federation,183.0,76.0
28996,28997,Yelena Shevchenko,Moscow,Moscow,RUS,Soviet Union,152.0,42.0
50495,50496,Yury Melnikov,Moscow,Moscow,RUS,Soviet Union,164.0,54.0
84394,84395,Jan de Man Lapidoth,Moscow,Moscow,RUS,Sweden,NaN,NaN
118717,118718,Aleksandra Patskevich,Moscow,Moscow,RUS,ROC Russian Federation,169.0,69.0
109399,109400,Aleksandr Ovechkin,Moscow,Moscow,RUS,Russian Federation,189.0,99.0
76728,76729,Irina Solontsova-Kudryavtseva,Moscow,Moscow,RUS,Soviet Union,181.0,89.0
96682,96683,Sergey Shakhray,Moscow,Moscow,RUS,Soviet Union,178.0,NaN
76576,76577,Olga Bogoslovskaya,Moscow,Moscow,RUS,Unified Team,166.0,54.0
23414,23415,Mark Rakita,Moscow,Moscow,RUS,Soviet Union,179.0,78.0
54453,54454,Nuzgari Mshvenieradze,Moscow,Moscow,RUS,Soviet Union,186.0,98.0
8439,8440,Anatoly Bulakov,Moscow,Moscow,RUS,Soviet Union,NaN,NaN
106603,106604,Mariya Gromova,Moscow,Moscow,RUS,Russian Federation,172.0,61.0
54413,54414,Viktor Ageyev,Moscow,Moscow,RUS,Soviet Union,184.0,80.0
90836,90837,Yelena Zamolodchikova,Moscow,Moscow,RUS,Russian Federation,154.0,43.0
136065,136066,Anna Frolova,Moscow,Moscow,RUS,Russian Federation,NaN,NaN
82188,82189,Marina Cherkasova,Moscow,Moscow,RUS,Russian Federation,164.0,62.0
27436,27437,Fyodor Cherenkov,Moscow,Moscow,RUS,Soviet Union,176.0,70.0

In [ ]:
bios['NOC']=bios['NOC'].replace({'Soviet Union': 'USSR'})
bios[bios['born_region']=='Moscow'].sample(20)

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
80944,80945,Nataliya Kurova,Moscow,Moscow,RUS,USSR,172.0,66.0
76655,76656,Nataliya Sokolova,Moscow,Moscow,RUS,USSR,164.0,55.0
129114,129115,Aleksandra Krunić,Moscow,Moscow,RUS,Serbia,167.0,53.0
27399,27400,Anatoly Maslyonkin,Moscow,Moscow,RUS,USSR,NaN,NaN
77117,77118,Nikolay Vikhor,Moscow,Moscow,RUS,USSR,192.0,118.0
50530,50531,Aleksandr Samsonov,Moscow,Moscow,RUS,USSR,187.0,80.0
136113,136114,Daniil Samsonov,Moscow,Moscow,RUS,Russian Federation,NaN,NaN
40083,40084,Vladimir Vasilyev,Moscow,Moscow,RUS,USSR,191.0,90.0
14969,14970,Lev Tsipursky,Moscow,Moscow,RUS,USSR,NaN,NaN
144029,144030,Anastasiya Fedotova,Moscow,Moscow,RUS,ROC,NaN,NaN
118241,118242,Valeriya Potyomkina-Reznik,Moscow,Moscow,RUS,Russian Federation,167.0,63.0
39846,39847,Lyudmila Krokhina,Moscow,Moscow,RUS,USSR,172.0,85.0
49664,49665,Olga Brusnikina,Moscow,Moscow,RUS,Russian Federation,169.0,55.0
11372,11373,Yelena Petushkova,Moscow,Moscow,RUS,USSR,160.0,65.0
27358,27359,Konstantin Beskov,Moscow,Moscow,RUS,USSR,NaN,NaN
31017,31018,Viktor Leontyev,Moscow,Moscow,RUS,USSR,168.0,63.0
114951,114952,Oksana Slivenko,Chekhov,Moscow,RUS,Russian Federation,164.0,69.0
44210,44211,Aleksandr Sokolov,Moscow,Moscow,RUS,USSR,173.0,73.0
142647,142648,Maksim Kabatsky,Moscow,Moscow,RUS,ROC,NaN,NaN
139008,139009,Alisa Ozhogina,Moscow,Moscow,RUS,Spain,173.0,58.0

In [158]:
mask=bios['NOC'].str.contains('Russian')
contains_russian=bios[mask]
contains_russian.sample(20)

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
98560,98561,Aleksandr Kibalko,Astana,Astana,KAZ,Russian Federation,183.0,85.0
43643,43644,Leonardus Syttin,Vilnius,Vilnius,LTU,Russian Federation,NaN,NaN
132863,132864,Aleksandr Markov,Ryazan,Ryazan,RUS,Russian Federation,179.0,70.0
118669,118670,Kseniya Dudkina,Omsk,Omsk,RUS,Russian Federation,173.0,49.0
23125,23126,Sergey Sharikov,Moscow,Moscow,RUS,Russian Federation,182.0,78.0
109578,109579,Nadezhda Orlova,NaN,NaN,NaN,Russian Federation,165.0,78.0
132865,132866,Sergey Khodos,Oskemen,Shyrgys Qazaqstan,KAZ,ROC Russian Federation,197.0,87.0
112362,112363,Viktor Keyru,Rostov-na-Donu,Rostov,RUS,Russian Federation,200.0,94.0
128996,128997,Gulnaz Gubaydullina,Novy Urengoy,Yamalo-Nenets Avtonomny Okrug,RUS,ROC Russian Federation,164.0,51.0
118783,118784,Larisa Pankova,Semey,Shyrgys Qazaqstan,KAZ,Russian Federation,176.0,52.0
108570,108571,Dmitry Vasilyev,Ufa,Respublika Bashkortostan,RUS,Russian Federation,178.0,67.0
100380,100381,Aleksey Tikhonov,Samara,Samara,RUS,Russian Federation,187.0,87.0
112357,112358,Viktor Khryapa,Kyiv,Kyiv,UKR,Russian Federation,206.0,107.0
23098,23099,Vladimir Andreyev,Voronezh,Voronezh,RUS,Russian Federation,NaN,NaN
105007,105008,Ruslan Nasibullin,Yekaterinburg,Sverdlovsk,RUS,Russian Federation,182.0,72.0
5296,5297,Yelena Khudashova,Khabarovsk,Khabarovsk Kray,RUS,Russian Federation Soviet Union Unified Team,195.0,78.0
126455,126456,Nikolay Khrenkov,Zheleznogorsk,Krasnoyarsk Kray,RUS,Russian Federation,185.0,95.0
91956,91957,Dmitry Kovalyov,Kaluga,Kaluga,RUS,Russian Federation,198.0,95.0
97576,97577,Andrey Trefilov,Kirovo-Chepetsk,Kirov,RUS,Russian Federation Unified Team,183.0,79.0
109825,109826,Nataliya Guseva,Tikhvin,Leningrad,RUS,Russian Federation,165.0,60.0

In [169]:
contains_russian['NOC']='Russian Federation'
contains_russian.sample(20)

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
94711,94712,Dmitry Mironov,Moscow,Moscow,RUS,Russian Federation,188.0,87.0
76690,76691,Nataliya Pomoshchnikova-Voronova,Moscow,Moscow,RUS,Russian Federation,169.0,63.0
119054,119055,Sergey Morgunov,Shakhty,Rostov,RUS,Russian Federation,178.0,70.0
106307,106308,Andrey Moiseyev,Rostov-na-Donu,Rostov,RUS,Russian Federation,195.0,83.0
136872,136873,Dmitry Knysh,NaN,NaN,NaN,Russian Federation,NaN,NaN
74793,74794,Irina Khudoroshkina,Tonarskiy,Quaraghandy,KAZ,Russian Federation,175.0,93.0
112462,112463,Dmitry Kovalyov,Omsk,Omsk,RUS,Russian Federation,180.0,80.0
74863,74864,Yevgeny Petrov,NaN,NaN,NaN,Russian Federation,171.0,68.0
59435,59436,Nikolajs Fārnasts,Rīga,Rīga,LAT,Russian Federation,NaN,NaN
93640,93641,Sergey Yermishin,Saratov,Saratov,RUS,Russian Federation,208.0,102.0
103577,103578,Oleg Perepechonov,Angren,Toshkent Viloyati,UZB,Russian Federation,165.0,77.0
32926,32927,Zulfiya Garipova,Kazan,Respublika Tatarstan,RUS,Russian Federation,167.0,56.0
117836,117837,Sergey Zinovyev,Viesīte,Viesītes novads,LAT,Russian Federation,178.0,81.0
111894,111895,Vera Andreyeva,Cheboksary,Chuvashkaya Respublika,RUS,Russian Federation,167.0,64.0
118831,118832,Yegor Nikolayev,Beloretsk,Respublika Bashkortostan,RUS,Russian Federation,176.0,60.0
128991,128992,Viktoriya Kalinina,Maykop,Respublika Adygeya,RUS,Russian Federation,183.0,74.0
80098,80099,Nataliya Buga,NaN,NaN,NaN,Russian Federation,160.0,56.0
96431,96432,Vadim Sayutin,Almaty,Almaty,KAZ,Russian Federation,188.0,80.0
85553,85554,Sergey Grinkov,Moscow,Moscow,RUS,Russian Federation,183.0,74.0
87788,87789,Olga Ryabinkina,Bryansk,Bryansk,RUS,Russian Federation,190.0,95.0

In [170]:
bios

,athlete_id,name,born_city,born_region,born_country,NOC,height_cm,weight_kg
0,1,Jean-François Blanchy,Bordeaux,Gironde,FRA,France,NaN,NaN
1,2,Arnaud Boetsch,Meulan,Yvelines,FRA,France,183.0,76.0
2,3,Jean Borotra,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0
3,4,Jacques Brugnon,Paris VIIIe,Paris,FRA,France,168.0,64.0
4,5,Albert Canet,Wandsworth,England,GBR,France,NaN,NaN
...,...,...,...,...,...,...,...,...
145495,145496,Polina Luchnikova,Serov,Sverdlovsk,RUS,ROC,167.0,61.0
145496,145497,Valeriya Merkusheva,Moscow,Moscow,RUS,ROC,168.0,65.0
145497,145498,Yuliya Smirnova,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0
145498,145499,André Foussard,Niort,Deux-Sèvres,FRA,France,166.0,NaN
145499,145500,Bill Phillips,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN