In [119]:
import pandas as pd

In [166]:
coffee=pd.read_csv('/Users/kseniaoblasova/Downloads/coffee.csv')
bios=pd.read_csv('/Users/kseniaoblasova/Downloads/bios.csv')

In [167]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [168]:
coffee.columns=coffee.columns.str.lower().str.replace(' ','_')
coffee

          day coffee_type  units_sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [169]:
bios[(bios['NOC'].isin(['ROC', 'Russian Federation','Soviet Union', 'Russia']))&(bios['name'].str.endswith('ova'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2178,2188,Nataliya Butuzova,1954-02-17,NaN,NaN,NaN,Soviet Union,167.0,58.0,NaN
2183,2193,Alla Peunova,1946-08-03,Donetsk,Donetsk,UKR,Soviet Union,169.0,NaN,NaN
2184,2194,Zebiniso Rustamova,1955-01-29,Dushanbe,Nohijahoi Tobei Çumhuri,TJK,Soviet Union,156.0,52.0,NaN
2523,2535,Anna Kournikova,1981-06-07,Moskva (Moscow),Moskva,RUS,Russian Federation,173.0,56.0,NaN
2525,2537,Yelena Makarova,1973-02-01,Moskva (Moscow),Moskva,RUS,Russian Federation,179.0,65.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145450,149174,Anna Shcherbakova,2004-03-28,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN
145487,149214,Yekaterina Kosova,1996-04-25,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN

In [170]:
coffee.head()

         day coffee_type  units_sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [171]:
coffee['price']=0.0
coffee.columns=coffee.columns.str.lower().str.replace(' ','_')
coffee

          day coffee_type  units_sold  price
0      Monday    Espresso          25    0.0
1      Monday       Latte          15    0.0
2     Tuesday    Espresso          30    0.0
3     Tuesday       Latte          20    0.0
4   Wednesday    Espresso          35    0.0
5   Wednesday       Latte          25    0.0
6    Thursday    Espresso          40    0.0
7    Thursday       Latte          30    0.0
8      Friday    Espresso          45    0.0
9      Friday       Latte          35    0.0
10   Saturday    Espresso          45    0.0
11   Saturday       Latte          35    0.0
12     Sunday    Espresso          45    0.0
13     Sunday       Latte          35    0.0

In [172]:
prices={'Espresso':3.50, 'Latte':4.50, 'Americano':2.99}

coffee.loc[14]=['Monday', 'Americano', 44, 0]

coffee['price']=coffee['coffee_type'].map(prices)
coffee

          day coffee_type  units_sold  price
0      Monday    Espresso          25   3.50
1      Monday       Latte          15   4.50
2     Tuesday    Espresso          30   3.50
3     Tuesday       Latte          20   4.50
4   Wednesday    Espresso          35   3.50
5   Wednesday       Latte          25   4.50
6    Thursday    Espresso          40   3.50
7    Thursday       Latte          30   4.50
8      Friday    Espresso          45   3.50
9      Friday       Latte          35   4.50
10   Saturday    Espresso          45   3.50
11   Saturday       Latte          35   4.50
12     Sunday    Espresso          45   3.50
13     Sunday       Latte          35   4.50
14     Monday   Americano          44   2.99

In [173]:
coffee['revenue']=coffee['units_sold']*coffee['price']
coffee

          day coffee_type  units_sold  price  revenue
0      Monday    Espresso          25   3.50    87.50
1      Monday       Latte          15   4.50    67.50
2     Tuesday    Espresso          30   3.50   105.00
3     Tuesday       Latte          20   4.50    90.00
4   Wednesday    Espresso          35   3.50   122.50
5   Wednesday       Latte          25   4.50   112.50
6    Thursday    Espresso          40   3.50   140.00
7    Thursday       Latte          30   4.50   135.00
8      Friday    Espresso          45   3.50   157.50
9      Friday       Latte          35   4.50   157.50
10   Saturday    Espresso          45   3.50   157.50
11   Saturday       Latte          35   4.50   157.50
12     Sunday    Espresso          45   3.50   157.50
13     Sunday       Latte          35   4.50   157.50
14     Monday   Americano          44   2.99   131.56

In [174]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [175]:
bios.insert(1, column='first_name', value=bios['name'].str.split().str[0])
bios

,athlete_id,first_name,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [176]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   first_name    145500 non-null  object
 2   name          145500 non-null  str
 3   born_date     143693 non-null  str
 4   born_city     110908 non-null  str
 5   born_region   110908 non-null  str
 6   born_country  110908 non-null  str
 7   NOC           145499 non-null  str
 8   height_cm     106651 non-null  float64
 9   weight_kg     102070 non-null  float64
 10  died_date     33940 non-null   str
dtypes: float64(2), int64(1), object(1), str(7)
memory usage: 12.2+ MB

In [177]:
bios['born_date']=pd.to_datetime(bios['born_date'])
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   first_name    145500 non-null  object
 2   name          145500 non-null  str
 3   born_date     143693 non-null  datetime64[us]
 4   born_city     110908 non-null  str
 5   born_region   110908 non-null  str
 6   born_country  110908 non-null  str
 7   NOC           145499 non-null  str
 8   height_cm     106651 non-null  float64
 9   weight_kg     102070 non-null  float64
 10  died_date     33940 non-null   str
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(6)
memory usage: 12.2+ MB

In [178]:
bios['born_year']=bios['born_date'].dt.year

bios[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [179]:
bios['height_category']=bios['height_cm'].apply(lambda x: 'Short' if x <165 else('Average'if 165<=x<=170 else('Tall' if x>170 else None)))
bios.sample(20)

,athlete_id,first_name,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_year,height_category
125687,128033,Shane,Shane Williamson,1995-04-28,Abashiri,Hokkaido,JPN,Japan,176.0,67.0,NaN,1995.0,Tall
119366,121169,Alexander,Alexander Kristoff,1987-07-05,Oslo,Oslo,NOR,Norway,180.0,72.0,NaN,1987.0,Tall
143920,147578,Fernando,Fernando González,1989-06-30,Barinas,Barinas,VEN,Venezuela,194.0,NaN,NaN,1989.0,Tall
119026,120808,Yukiya,Yukiya Arashiro,1984-09-22,Ishigaki,Okinawa,JPN,Japan,171.0,64.0,NaN,1984.0,Tall
115444,116797,Deng,Deng Jian,1989-10-19,NaN,NaN,NaN,People's Republic of China,182.0,75.0,NaN,1989.0,Tall
72389,72938,Kim,Kim Gi-Hun,1968-05-27,NaN,NaN,NaN,Republic of Korea,177.0,93.0,NaN,1968.0,Tall
4974,4992,Luis,Luis Portillo,1956-09-29,San Miguel de Tucumán,Tucumán,ARG,Argentina,175.0,64.0,NaN,1956.0,Tall
4842,4860,Hjalmar,Hjalmar Strømme,1900-09-26,Bergen,Vestland,NOR,Norway,NaN,NaN,1925-12-15,1900.0,NaN
36036,36321,Rodolfo,Rodolfo Pereira,1959-09-20,NaN,NaN,NaN,Chile,NaN,NaN,NaN,1959.0,NaN
25477,25668,Sándor,Sándor Bodnár,1890-09-20,Budapest,Budapest,HUN,Hungary,NaN,NaN,1955-11-06,1890.0,NaN
15271,15375,Josef,Josef Lošek,1912-03-14,NaN,NaN,NaN,Czechoslovakia,NaN,NaN,NaN,1912.0,NaN
97045,97825,Boris,Boris Stenin,1935-01-17,Arti,Sverdlovsk,RUS,Soviet Union,171.0,71.0,2001-01-18,1935.0,Tall
104037,105036,DeeDee,DeeDee Trotter,1982-12-08,Twentynine Palms,California,USA,United States,178.0,64.0,NaN,1982.0,Tall
103660,104649,Gleb,Gleb Pisarevsky,1976-06-28,Arkhangelsk,Arkhangelsk,RUS,Russian Federation,182.0,108.0,NaN,1976.0,Tall
58821,59241,Aigars,Aigars Jansons,1971-07-27,Sigulda,Siguldas novads,LAT,Latvia,163.0,62.0,NaN,1971.0,Short
31201,31437,Charles,Charles Simms,1928-01-24,New York,New York,USA,United States,172.0,70.0,2003-10-10,1928.0,Tall
20289,20433,Walter,Walter Stude,1913-12-03,Kingston,Ontario,CAN,United States,185.0,95.0,1991-10-25,1913.0,Tall
120077,121931,Ding,Ding Ning,1990-06-20,Anda,Heilongjiang,CHN,People's Republic of China,171.0,63.0,NaN,1990.0,Tall
18636,18764,Robin,Robin Fletcher,1922-05-30,Guildford,England,GBR,Great Britain,NaN,NaN,2016-01-15,1922.0,NaN
99131,99929,Andrea,Andrea Pais de Libera,1973-03-29,Auronzo di Cadore,Belluno,ITA,Italy,188.0,95.0,NaN,1973.0,Tall

In [180]:
nocs=pd.read_csv('/Users/kseniaoblasova/Downloads/noc_regions.csv')
nocs

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

In [181]:
pass

In [182]:
coffee

          day coffee_type  units_sold  price  revenue
0      Monday    Espresso          25   3.50    87.50
1      Monday       Latte          15   4.50    67.50
2     Tuesday    Espresso          30   3.50   105.00
3     Tuesday       Latte          20   4.50    90.00
4   Wednesday    Espresso          35   3.50   122.50
5   Wednesday       Latte          25   4.50   112.50
6    Thursday    Espresso          40   3.50   140.00
7    Thursday       Latte          30   4.50   135.00
8      Friday    Espresso          45   3.50   157.50
9      Friday       Latte          35   4.50   157.50
10   Saturday    Espresso          45   3.50   157.50
11   Saturday       Latte          35   4.50   157.50
12     Sunday    Espresso          45   3.50   157.50
13     Sunday       Latte          35   4.50   157.50
14     Monday   Americano          44   2.99   131.56

In [183]:
import numpy as np
coffee.loc[[2,3], 'units_sold']=np.nan
coffee

          day coffee_type  units_sold  price  revenue
0      Monday    Espresso        25.0   3.50    87.50
1      Monday       Latte        15.0   4.50    67.50
2     Tuesday    Espresso         NaN   3.50   105.00
3     Tuesday       Latte         NaN   4.50    90.00
4   Wednesday    Espresso        35.0   3.50   122.50
5   Wednesday       Latte        25.0   4.50   112.50
6    Thursday    Espresso        40.0   3.50   140.00
7    Thursday       Latte        30.0   4.50   135.00
8      Friday    Espresso        45.0   3.50   157.50
9      Friday       Latte        35.0   4.50   157.50
10   Saturday    Espresso        45.0   3.50   157.50
11   Saturday       Latte        35.0   4.50   157.50
12     Sunday    Espresso        45.0   3.50   157.50
13     Sunday       Latte        35.0   4.50   157.50
14     Monday   Americano        44.0   2.99   131.56

In [187]:
coffee['units_sold']=coffee['units_sold'].interpolate()
coffee

          day coffee_type  units_sold  price  revenue
0      Monday    Espresso   25.000000   3.50    87.50
1      Monday       Latte   15.000000   4.50    67.50
2     Tuesday    Espresso   21.666667   3.50   105.00
3     Tuesday       Latte   28.333333   4.50    90.00
4   Wednesday    Espresso   35.000000   3.50   122.50
5   Wednesday       Latte   25.000000   4.50   112.50
6    Thursday    Espresso   40.000000   3.50   140.00
7    Thursday       Latte   30.000000   4.50   135.00
8      Friday    Espresso   45.000000   3.50   157.50
9      Friday       Latte   35.000000   4.50   157.50
10   Saturday    Espresso   45.000000   3.50   157.50
11   Saturday       Latte   35.000000   4.50   157.50
12     Sunday    Espresso   45.000000   3.50   157.50
13     Sunday       Latte   35.000000   4.50   157.50
14     Monday   Americano   44.000000   2.99   131.56

In [ ]:
coffee.groupby(['coffee_type']).agg({'units_sold':'sum', 'price':'mean'})

             units_sold  price
coffee_type
Americano     44.000000   2.99
Espresso     256.666667   3.50
Latte        203.333333   4.50

In [200]:
coffee

          day coffee_type  units_sold  price  revenue
0      Monday    Espresso   25.000000   3.50    87.50
1      Monday       Latte   15.000000   4.50    67.50
2     Tuesday    Espresso   21.666667   3.50   105.00
3     Tuesday       Latte   28.333333   4.50    90.00
4   Wednesday    Espresso   35.000000   3.50   122.50
5   Wednesday       Latte   25.000000   4.50   112.50
6    Thursday    Espresso   40.000000   3.50   140.00
7    Thursday       Latte   30.000000   4.50   135.00
8      Friday    Espresso   45.000000   3.50   157.50
9      Friday       Latte   35.000000   4.50   157.50
10   Saturday    Espresso   45.000000   3.50   157.50
11   Saturday       Latte   35.000000   4.50   157.50
12     Sunday    Espresso   45.000000   3.50   157.50
13     Sunday       Latte   35.000000   4.50   157.50
14     Monday   Americano   44.000000   2.99   131.56

In [202]:
bios.head()

,athlete_id,first_name,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_year,height_category
0,1,Jean-François,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886.0,NaN
1,2,Arnaud,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969.0,Tall
2,3,Jean,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898.0,Tall
3,4,Jacques,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895.0,Average
4,5,Albert,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878.0,NaN

In [206]:
bios.groupby('born_year')['name'].count().max()

np.int64(2231)

In [ ]:
bios['NOC'].str.count