In [3]:
import pandas as pd

In [16]:
df=pd.read_csv('/Users/kseniaoblasova/Desktop/tallest_people_in_the_world.csv')
df

,id,name,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition,is_alive
0,1,John F. Carroll,Male,USA,North America,264,8 ft 8 in,140.0,1932,1969.0,37,NaN,Acromegaly,0
1,2,Robert Wadlow,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism,0
2,3,John Rogan,Male,USA,North America,267,8 ft 9 in,79.0,1868,1905.0,37,Seller,Gigantism,0
3,4,Willie Camper,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism,0
4,5,Siah Khan,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,6 ft 10.7 in,NaN,1964,NaN,62,Athlete,Genetic,1
153,154,Miranda Weber,Female,Canada,North America,211,6 ft 11 in,NaN,1982,NaN,44,Athlete,Genetic,1
154,155,Uljana Semjonova,Female,Latvia,Europe,213,7 ft 0 in,120.0,1952,NaN,74,Athlete,Genetic,1
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,6 ft 10.7 in,NaN,1819,1854.0,35,Entertainer,Gigantism,0
156,157,Han Xu,Female,China,Asia,211,6 ft 11 in,88.0,1999,NaN,27,Athlete,Genetic,1

In [18]:
df=df.drop(columns='is_alive')
df

,id,name,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition
0,1,John F. Carroll,Male,USA,North America,264,8 ft 8 in,140.0,1932,1969.0,37,NaN,Acromegaly
1,2,Robert Wadlow,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism
2,3,John Rogan,Male,USA,North America,267,8 ft 9 in,79.0,1868,1905.0,37,Seller,Gigantism
3,4,Willie Camper,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism
4,5,Siah Khan,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,6 ft 10.7 in,NaN,1964,NaN,62,Athlete,Genetic
153,154,Miranda Weber,Female,Canada,North America,211,6 ft 11 in,NaN,1982,NaN,44,Athlete,Genetic
154,155,Uljana Semjonova,Female,Latvia,Europe,213,7 ft 0 in,120.0,1952,NaN,74,Athlete,Genetic
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,6 ft 10.7 in,NaN,1819,1854.0,35,Entertainer,Gigantism
156,157,Han Xu,Female,China,Asia,211,6 ft 11 in,88.0,1999,NaN,27,Athlete,Genetic

In [19]:
df.head(10)

,id,name,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition
0,1,John F. Carroll,Male,USA,North America,264,8 ft 8 in,140.0,1932,1969.0,37,NaN,Acromegaly
1,2,Robert Wadlow,Male,USA,North America,272,8 ft 11 in,199.0,1918,1940.0,22,Entertainer,Gigantism
2,3,John Rogan,Male,USA,North America,267,8 ft 9 in,79.0,1868,1905.0,37,Seller,Gigantism
3,4,Willie Camper,Male,USA,North America,260,8 ft 6.3 in,170.0,1924,1943.0,18,Entertainer,Gigantism
4,5,Siah Khan,Male,Iran,Asia,259,8 ft 6 in,155.0,1913,1939.0,26,Entertainer,Gigantism
5,6,Akashi Shiganosuke,Male,Japan,Asia,254,8 ft 4 in,185.0,1600,1649.0,49,Athlete,Gigantism
6,7,Vrolijk de Beers,Male,Malawi,Africa,246,8 ft 1 in,130.0,1925,1961.0,36,Entertainer,Gigantism
7,8,Ho Van Trung,Male,Vietnam,Asia,257,8 ft 5 in,158.0,1984,2019.0,35,Farmer,Gigantism
8,9,Pornchai Saosri,Male,Thailand,Asia,269,8 ft 10 in,NaN,1989,2015.0,26,NaN,Gigantism
9,10,Bernard Coyne,Male,USA,North America,249,8 ft 2 in,NaN,1897,1921.0,24,NaN,Gigantism

In [20]:
df.tail()

,id,name,gender,country,continent,height_cm,height_ft_in,weight_kg,birth_year,death_year,lifespan,occupation,medical_condition
152,153,Jaana Kotova,Female,Estonia,Europe,210,6 ft 10.7 in,NaN,1964,NaN,62,Athlete,Genetic
153,154,Miranda Weber,Female,Canada,North America,211,6 ft 11 in,NaN,1982,NaN,44,Athlete,Genetic
154,155,Uljana Semjonova,Female,Latvia,Europe,213,7 ft 0 in,120.0,1952,NaN,74,Athlete,Genetic
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,6 ft 10.7 in,NaN,1819,1854.0,35,Entertainer,Gigantism
156,157,Han Xu,Female,China,Asia,211,6 ft 11 in,88.0,1999,NaN,27,Athlete,Genetic

In [23]:
df.info()
df.shape
df.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 157 non-null    int64
 1   name               157 non-null    str
 2   gender             157 non-null    str
 3   country            157 non-null    str
 4   continent          157 non-null    str
 5   height_cm          157 non-null    int64
 6   height_ft_in       157 non-null    str
 7   weight_kg          74 non-null     float64
 8   birth_year         157 non-null    int64
 9   death_year         84 non-null     float64
 10  lifespan           157 non-null    int64
 11  occupation         111 non-null    str
 12  medical_condition  157 non-null    str
dtypes: float64(2), int64(4), str(7)
memory usage: 16.1 KB

id                     int64
name                     str
gender                   str
country                  str
continent                str
height_cm              int64
height_ft_in             str
weight_kg            float64
birth_year             int64
death_year           float64
lifespan               int64
occupation               str
medical_condition        str
dtype: object

In [24]:
df=df.drop(columns=['height_ft_in', 'death_year'])
df

,id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,occupation,medical_condition
0,1,John F. Carroll,Male,USA,North America,264,140.0,1932,37,NaN,Acromegaly
1,2,Robert Wadlow,Male,USA,North America,272,199.0,1918,22,Entertainer,Gigantism
2,3,John Rogan,Male,USA,North America,267,79.0,1868,37,Seller,Gigantism
3,4,Willie Camper,Male,USA,North America,260,170.0,1924,18,Entertainer,Gigantism
4,5,Siah Khan,Male,Iran,Asia,259,155.0,1913,26,Entertainer,Gigantism
...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,NaN,1964,62,Athlete,Genetic
153,154,Miranda Weber,Female,Canada,North America,211,NaN,1982,44,Athlete,Genetic
154,155,Uljana Semjonova,Female,Latvia,Europe,213,120.0,1952,74,Athlete,Genetic
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,NaN,1819,35,Entertainer,Gigantism
156,157,Han Xu,Female,China,Asia,211,88.0,1999,27,Athlete,Genetic

In [36]:
df.filter(regex=r'^\w+_\w+$')

     height_cm  weight_kg  birth_year medical_condition
0          264      140.0        1932        Acromegaly
1          272      199.0        1918         Gigantism
2          267       79.0        1868         Gigantism
3          260      170.0        1924         Gigantism
4          259      155.0        1913         Gigantism
..         ...        ...         ...               ...
152        210        NaN        1964           Genetic
153        211        NaN        1982           Genetic
154        213      120.0        1952           Genetic
155        210        NaN        1819         Gigantism
156        211       88.0        1999           Genetic

[157 rows x 4 columns]

In [44]:
df.rename(columns={'height':'height_cm', 'weight':'weight_kg'}, inplace=True)
df

,id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,occupation,medical_condition
0,person_id,John F. Carroll,Male,USA,North America,264,140.0,1932,37,NaN,Acromegaly
1,person_id,Robert Wadlow,Male,USA,North America,272,199.0,1918,22,Entertainer,Gigantism
2,person_id,John Rogan,Male,USA,North America,267,79.0,1868,37,Seller,Gigantism
3,person_id,Willie Camper,Male,USA,North America,260,170.0,1924,18,Entertainer,Gigantism
4,person_id,Siah Khan,Male,Iran,Asia,259,155.0,1913,26,Entertainer,Gigantism
...,...,...,...,...,...,...,...,...,...,...,...
152,person_id,Jaana Kotova,Female,Estonia,Europe,210,NaN,1964,62,Athlete,Genetic
153,person_id,Miranda Weber,Female,Canada,North America,211,NaN,1982,44,Athlete,Genetic
154,person_id,Uljana Semjonova,Female,Latvia,Europe,213,120.0,1952,74,Athlete,Genetic
155,person_id,Kristina Larsdotter,Female,Sweden,Europe,210,NaN,1819,35,Entertainer,Gigantism
156,person_id,Han Xu,Female,China,Asia,211,88.0,1999,27,Athlete,Genetic

In [54]:
df['person_id']=range(1, len(df)+1)
df

,person_id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,occupation,medical_condition,id
0,1,John F. Carroll,Male,USA,North America,264,140.0,1932,37,NaN,Acromegaly,something
1,2,Robert Wadlow,Male,USA,North America,272,199.0,1918,22,Entertainer,Gigantism,something
2,3,John Rogan,Male,USA,North America,267,79.0,1868,37,Seller,Gigantism,something
3,4,Willie Camper,Male,USA,North America,260,170.0,1924,18,Entertainer,Gigantism,something
4,5,Siah Khan,Male,Iran,Asia,259,155.0,1913,26,Entertainer,Gigantism,something
...,...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,NaN,1964,62,Athlete,Genetic,something
153,154,Miranda Weber,Female,Canada,North America,211,NaN,1982,44,Athlete,Genetic,something
154,155,Uljana Semjonova,Female,Latvia,Europe,213,120.0,1952,74,Athlete,Genetic,something
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,NaN,1819,35,Entertainer,Gigantism,something
156,157,Han Xu,Female,China,Asia,211,88.0,1999,27,Athlete,Genetic,something

In [55]:
df.rename(columns={'person_id':'id'}, inplace=True)
df

,id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,occupation,medical_condition,id
0,1,John F. Carroll,Male,USA,North America,264,140.0,1932,37,NaN,Acromegaly,something
1,2,Robert Wadlow,Male,USA,North America,272,199.0,1918,22,Entertainer,Gigantism,something
2,3,John Rogan,Male,USA,North America,267,79.0,1868,37,Seller,Gigantism,something
3,4,Willie Camper,Male,USA,North America,260,170.0,1924,18,Entertainer,Gigantism,something
4,5,Siah Khan,Male,Iran,Asia,259,155.0,1913,26,Entertainer,Gigantism,something
...,...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,NaN,1964,62,Athlete,Genetic,something
153,154,Miranda Weber,Female,Canada,North America,211,NaN,1982,44,Athlete,Genetic,something
154,155,Uljana Semjonova,Female,Latvia,Europe,213,120.0,1952,74,Athlete,Genetic,something
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,NaN,1819,35,Entertainer,Gigantism,something
156,157,Han Xu,Female,China,Asia,211,88.0,1999,27,Athlete,Genetic,something

In [65]:
df=df.iloc[:,:-1]
df

,id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,occupation,medical_condition
0,1,John F. Carroll,Male,USA,North America,264,140.0,1932,37,NaN,Acromegaly
1,2,Robert Wadlow,Male,USA,North America,272,199.0,1918,22,Entertainer,Gigantism
2,3,John Rogan,Male,USA,North America,267,79.0,1868,37,Seller,Gigantism
3,4,Willie Camper,Male,USA,North America,260,170.0,1924,18,Entertainer,Gigantism
4,5,Siah Khan,Male,Iran,Asia,259,155.0,1913,26,Entertainer,Gigantism
...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,NaN,1964,62,Athlete,Genetic
153,154,Miranda Weber,Female,Canada,North America,211,NaN,1982,44,Athlete,Genetic
154,155,Uljana Semjonova,Female,Latvia,Europe,213,120.0,1952,74,Athlete,Genetic
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,NaN,1819,35,Entertainer,Gigantism
156,157,Han Xu,Female,China,Asia,211,88.0,1999,27,Athlete,Genetic

In [67]:
df=df.iloc[:,:-1]
df

,id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,occupation,medical_condition
0,1,John F. Carroll,Male,USA,North America,264,140.0,1932,37,NaN,Acromegaly
1,2,Robert Wadlow,Male,USA,North America,272,199.0,1918,22,Entertainer,Gigantism
2,3,John Rogan,Male,USA,North America,267,79.0,1868,37,Seller,Gigantism
3,4,Willie Camper,Male,USA,North America,260,170.0,1924,18,Entertainer,Gigantism
4,5,Siah Khan,Male,Iran,Asia,259,155.0,1913,26,Entertainer,Gigantism
...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,NaN,1964,62,Athlete,Genetic
153,154,Miranda Weber,Female,Canada,North America,211,NaN,1982,44,Athlete,Genetic
154,155,Uljana Semjonova,Female,Latvia,Europe,213,120.0,1952,74,Athlete,Genetic
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,NaN,1819,35,Entertainer,Gigantism
156,157,Han Xu,Female,China,Asia,211,88.0,1999,27,Athlete,Genetic

In [68]:
df.insert(loc=9, column='death_year', value=df['birth_year']+df['lifespan'])
df

,id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,death_year,occupation,medical_condition
0,1,John F. Carroll,Male,USA,North America,264,140.0,1932,37,1969,NaN,Acromegaly
1,2,Robert Wadlow,Male,USA,North America,272,199.0,1918,22,1940,Entertainer,Gigantism
2,3,John Rogan,Male,USA,North America,267,79.0,1868,37,1905,Seller,Gigantism
3,4,Willie Camper,Male,USA,North America,260,170.0,1924,18,1942,Entertainer,Gigantism
4,5,Siah Khan,Male,Iran,Asia,259,155.0,1913,26,1939,Entertainer,Gigantism
...,...,...,...,...,...,...,...,...,...,...,...,...
152,153,Jaana Kotova,Female,Estonia,Europe,210,NaN,1964,62,2026,Athlete,Genetic
153,154,Miranda Weber,Female,Canada,North America,211,NaN,1982,44,2026,Athlete,Genetic
154,155,Uljana Semjonova,Female,Latvia,Europe,213,120.0,1952,74,2026,Athlete,Genetic
155,156,Kristina Larsdotter,Female,Sweden,Europe,210,NaN,1819,35,1854,Entertainer,Gigantism
156,157,Han Xu,Female,China,Asia,211,88.0,1999,27,2026,Athlete,Genetic

In [74]:
mask=df['name'].str.endswith('ova')
tall_slavics=df[mask]
print(tall_slavics)

      id              name  gender  country continent  height_cm  weight_kg  \
152  153      Jaana Kotova  Female  Estonia    Europe        210        NaN
154  155  Uljana Semjonova  Female   Latvia    Europe        213      120.0

     birth_year  lifespan  death_year occupation medical_condition
152        1964        62        2026    Athlete           Genetic
154        1952        74        2026    Athlete           Genetic

In [ ]:
df.loc[(df['death_year']==2026)&(df['lifespan']<100)]=None
df

,id,name,gender,country,continent,height_cm,weight_kg,birth_year,lifespan,death_year,occupation,medical_condition
0,1.0,John F. Carroll,Male,USA,North America,264.0,140.0,1932.0,37.0,1969.0,NaN,Acromegaly
1,2.0,Robert Wadlow,Male,USA,North America,272.0,199.0,1918.0,22.0,1940.0,Entertainer,Gigantism
2,3.0,John Rogan,Male,USA,North America,267.0,79.0,1868.0,37.0,1905.0,Seller,Gigantism
3,4.0,Willie Camper,Male,USA,North America,260.0,170.0,1924.0,18.0,1942.0,Entertainer,Gigantism
4,5.0,Siah Khan,Male,Iran,Asia,259.0,155.0,1913.0,26.0,1939.0,Entertainer,Gigantism
...,...,...,...,...,...,...,...,...,...,...,...,...
152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,156.0,Kristina Larsdotter,Female,Sweden,Europe,210.0,NaN,1819.0,35.0,1854.0,Entertainer,Gigantism
156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN